### ISSUE TITLE
Bug: River update to 0.21.1 -> CA-Wrapper fails for DenStream

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro-Int-River#13]
**1 Describe the bug**
River's update to 0.21.1 caused a fail of our wrapper for cluster analyzer DENStream.

**2 To Reproduce**
1. Install River 0.21.1
2. Run howto_oa_wr_003_river_clusteranalyzer_denstream.py

**3 Expected behavior**
The mentioned howto should run without an error.

**4 Screenshots**
**2024-04-29  07:57:21.068569  S  River Cluster Analyzer DenStream "t1": Adaptation started
2024-04-29  07:57:21.078209  I  River Cluster Analyzer DenStream "t1": Cluster is adapted...**
Traceback (most recent call last):
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro_int_river\wrappers\clusteranalyzers.py", line 684, in get_clusters
    related_cluster = self._clusters[id(val)]
                      ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 1498598195600

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\detle\Development\github\fhswf\MLPro-Int-River\test\howtos\oa\howto_oa_wr_003_river_clusteranalyzer_denstream.py.off", line 174, in <module>
    myscenario.run()
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\ops.py", line 404, in run
    success, error, timeout, limit, adapted_cycle, end_of_data = self.run_cycle()       
                                                                 ^^^^^^^^^^^^^^^^       
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\ops.py", line 296, in run_cycle
    success, error, adapted, end_of_data = self._run_cycle()
                                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\streams\models.py", line 1768, in _run_cycle
    self._workflow.run( p_inst_new = inst_new, p_inst_del=[] )
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\streams\models.py", line 1580, in run
    Workflow.run(self, p_range=p_range, p_wait=p_wait)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\mt.py", line 1045, in run
    task.run( p_range=range_run, **p_kwargs )
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\streams\models.py", line 934, in run
    Task.run(self, p_range=p_range, p_wait=p_wait, p_inst_new=inst_new, p_inst_del=inst_del)
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\mt.py", line 612, in run
    self._start_async( p_target=self._run_async, p_range=self._range_run, **p_kwargs )  
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\mt.py", line 429, in _start_async
    p_target(**p_kwargs)
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\mt.py", line 632, in _run_async
    self._custom_run_method(**p_kwargs)
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\bf\streams\models.py", line 945, in _run_wrapper
    self._run( p_inst_new = p_inst_new, p_inst_del=p_inst_del )
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\oa\streams\tasks\clusteranalyzers\basics.py", line 127, in _run
    self.adapt( p_inst_new=p_inst_new, p_inst_del=p_inst_del )
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro\oa\streams\basics.py", line 124, in adapt
    adapted = self._adapt( p_inst_new=p_inst_new )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro_int_river\wrappers\clusteranalyzers.py", line 154, in _adapt
    self.get_clusters()
  File "C:\Users\detle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mlpro_int_river\wrappers\clusteranalyzers.py", line 693, in get_clusters
    p_cluster=self._river_algo.clusters[key],
              ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
**KeyError: 0**


**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
Hi @steveyuwono, this has not the highest priority. I disabled the mentioned howto. Maybe we can assess the behaviour again on the next version of River...

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, this has not the highest priority. I disabled the mentioned howto. Maybe we can assess the behaviour again on the next version of River...

Hi @detlefarend , this is typical for the latest version. I checked the updated source code and they have modified the distance calculation function which somehow also affects some other related functions. But I have figured this out, reactivated the howto 003, and merged the branch to the main.

**Comment by detlefarend** [comment]
> > Hi @steveyuwono, this has not the highest priority. I disabled the mentioned howto. Maybe we can assess the behaviour again on the next version of River...
> 
> Hi @detlefarend , this is typical for the latest version. I checked the updated source code and they have modified the distance calculation function which somehow also affects some other related functions as well as the workflow of introducing clusters. But I have figured this out, reactivated the howto 003, and merged the branch to the main.

Ah wow. Thank you for the very fast solution!!
